# ==========================================
# Application Configuration
# ==========================================
spring.application.name=SchedulerSystem
# Set the server port
server.port=${PORT:8080}

# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=${DB_URL:jdbc:h2:mem:schedulerdb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Explicitly define how Hibernate handles the schema